default:
  - &default_tag 3.0.1-rc6
  - &default_pull_policy Never
  - &default_host kraken-local
  - &default_admin_username "kraken-demo"
  - &default_admin_password "pv68cxUKNZvy3vSZH78B"
  - &kraken_local_ip 192.168.1.13

### INGRESS CONFIGURATION ###

host:
  name: *default_host
  ip: *kraken_local_ip
  scheme: http

### BACKEND CONFIGURATION ###

backend:
  image:
    tag: *default_tag
    pullPolicy: *default_pull_policy
  licenseFile: |
    eyJraWQiOiJrcmFrZW4iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJrcmFrZW4iLCJuYmYiOjE1OTI4MzkwMzQsImhvc3RzIjozLCJpc3MiOiJvY3RvcGVyZi5jb20iLCJleHAiOjQ3NDY0MzkwMzQsImlhdCI6MTU5MjgzOTAzNH0.kZFjQK0lw96Q_vKme1YMSvNj8IcG3qwpxgCvMMLfEqcr1KS-Bn5DhCcAsKfjQIrne2UjxDNLTRRrpQiM4gCIifXVPwvd0KxwpD-oN9mGUChRBKdjhgcEf9lFPiLG-jzpXQranWISSrt2jcGO0giTADZIPu9jcqqVX9MZaZQz-1ojUzIaAyHvVqXGFJYw4ukDeZggUfjKIVvn38jhhdsS0RzuF3TQJdGu_pXzMvcktbhGKjrVTEhWRJN9M9oIsDL7m9egMzEvCe3KzFY1-otmMjeZzeVfvASS2GQYzacBZd8ohVArx4g1bYFmou7AEDqO6z9PSgPGkdJIiyFgU67Zbg
  persistence:
    size: 4Gi

### DOCUMENTATION CONFIGURATION ###

documentation:
  image:
    tag: *default_tag
    pullPolicy: *default_pull_policy

### FRONTEND CONFIGURATION ###

frontend:
  administration:
    image:
      tag: *default_tag
      pullPolicy: *default_pull_policy
  gatling:
    image:
      tag: *default_tag
      pullPolicy: *default_pull_policy

### GRAFANA CONFIGURATION ###

grafana:
  persistence:
    size: 2Gi
  admin:
    username: *default_admin_username
    password: *default_admin_password

### INFLUXDB CONFIGURATION ###

influxdb:
  persistence:
    size: 5Gi
  admin:
    username: *default_admin_username
    password: *default_admin_password

### KEYCLOAK CONFIGURATION ###

keycloak:
  image:
    tag: *default_tag
    pullPolicy: *default_pull_policy
  admin:
    username: *default_admin_username
    password: *default_admin_password
  config:
    recaptcha:
      enabled: true
      key: 6LcPAvkUAAAAAIBM3Ei6mS74W1BUyG4aNFUSpswC
      secret: 6LcPAvkUAAAAABONZ8ztd8K9RIDA26j21EUNMn8o
    mail:
      enabled: true
      password: XxJFQvj6RCJqPvEZmHcN9w
      starttls: false
      auth: true
      port: 587
      host: smtp.mandrillapp.com
      replyTo: support@octoperf.com
      from: support@octoperf.com
      fromDisplayName: Kraken
      ssl: null
      user: support@jellly.io
    client:
      web:
        secret: ed5974bb-e711-5b8b-9315-6ad315361f33
      api:
        secret: c1ab32c0-0ba7-5289-b6c9-0ea1aa5ad1d5
      container:
        secret: 6caa811c-5a41-5a53-aa5d-51c575330147

### POSTGRES CONFIGURATION ###

postgres:
  persistence:
    size: 1Gi
  admin:
    databaseKeycloak: keycloak-demo
    databaseGrafana: grafana-demo
    username: *default_admin_username
    password: *default_admin_password