version: '3.7'

services:
  kraken-influxdb-dev:
    image: influxdb:1.7.4
    container_name: kraken-influxdb-dev
    network_mode: host
    expose:
      - "8086"
    env_file:
      - 'influxdb/env.influxdb'
    volumes:
      - ./analysis/influxdb:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  kraken-grafana-dev:
    user: ${KRAKEN_HOST_UID}:${KRAKEN_HOST_GID}
    image: grafana/grafana:6.7.1
    container_name: kraken-grafana-dev
    network_mode: host
    expose:
      - "3000"
    env_file:
      - 'grafana/env.grafana'
    volumes:
      - ./analysis/grafana:/var/lib/grafana
#      - ./grafana/provisioning:/etc/grafana/provisioning
#      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
#
#  kraken-haproxy-dev:
#    image: haproxy:1.9.5-alpine
#    container_name: kraken-haproxy-dev
#    network_mode: host
#    expose:
#      - "8300"
#    volumes:
#      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
#    depends_on:
#      - kraken-grafana-dev
#    restart: unless-stopped

  kraken-postgres-dev:
    image: postgres:12.2
    container_name: kraken-postgres-dev
    network_mode: host
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  kraken-keycloak-dev:
    image: quay.io/keycloak/keycloak:9.0.2
    container_name: kraken-keycloak-dev
    network_mode: host
    environment:
      DB_VENDOR: "POSTGRES"
      DB_ADDR: "localhost"
      DB_DATABASE: "keycloak"
      DB_USER: "keycloak"
      DB_SCHEMA: "public"
      DB_PASSWORD: "password"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "kraken"
      KEYCLOAK_WELCOME_THEME: "kraken"
      KRAKEN_SECURITY_URL: "http://kraken.local:9080"
      KRAKEN_URLS: "http://kraken.local:8080/user-events,http://kraken.local:8081/user-events"
      KRAKEN_SECURITY_API_ID: "kraken-api"
      KRAKEN_SECURITY_API_SECRET: "c1ab32c0-0ba7-4289-b6c9-0ea1aa5ad1d4"
      KRAKEN_SECURITY_REALM: "kraken"
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
      - ./keycloak/themes/kraken:/opt/jboss/keycloak/themes/kraken
      - ./keycloak/deployments:/opt/jboss/keycloak/standalone/deployments
    expose:
      - 9080
    depends_on:
      - kraken-postgres-dev
    command:
      - "-Djboss.bind.address.private=127.0.0.1 -Djboss.bind.address=0.0.0.0 -Djboss.socket.binding.port-offset=1000 -Dkeycloak.profile=preview -Dkeycloak.import=/opt/jboss/keycloak/imports/kraken-realm.json"