version: '3.5'

services:
  kraken-gatling-debugger:
    image: "octoperf/kraken-gatling-runner:${KRAKEN_VERSION}"
    container_name: "${KRAKEN_TASKID}-${KRAKEN_GATLING_CONTAINER_NAME}_STARTING"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "${KRAKEN_GATLING_CPU_LIMIT}"
          memory: "${KRAKEN_GATLING_MEMORY_LIMIT}"
        reservations:
          cpus: "${KRAKEN_GATLING_CPU_REQUEST}"
          memory: "${KRAKEN_GATLING_MEMORY_REQUEST}"
    labels:
      com.kraken/taskId: "${KRAKEN_TASKID}"
      com.kraken/taskType: "${KRAKEN_TASKTYPE}"
      com.kraken/containerName: "${KRAKEN_TASKID}-${KRAKEN_GATLING_CONTAINER_NAME}"
      com.kraken/hostId: "${KRAKEN_HOSTID}"
      com.kraken/label: "${KRAKEN_GATLING_CONTAINER_LABEL}"
      com.kraken/description: "${KRAKEN_DESCRIPTION}"
      com.kraken/expectedCount: "${KRAKEN_EXPECTED_COUNT}"
      com.kraken/applicationId: "${KRAKEN_APPLICATION_ID}"
    environment:
      KRAKEN_CONTAINER_TASKID: "${KRAKEN_TASKID}"
      KRAKEN_CONTAINER_TASKTYPE: "${KRAKEN_TASKTYPE}"
      KRAKEN_CONTAINER_NAME: "${KRAKEN_TASKID}-${KRAKEN_GATLING_CONTAINER_NAME}"
      KRAKEN_CONTAINER_HOSTID: "${KRAKEN_HOSTID}"
      KRAKEN_GATLING_SIMULATION_NAME: "${KRAKEN_GATLING_SIMULATION_NAME}"
      KRAKEN_GATLING_DESCRIPTION: "${KRAKEN_DESCRIPTION}"
      KRAKEN_GATLING_JAVAOPTS: "${KRAKEN_GATLING_JAVAOPTS} -Xmx${KRAKEN_GATLING_XMX}"
      KRAKEN_RUNTIME_URL: "${KRAKEN_RUNTIME_URL}"
      KRAKEN_STORAGE_URL: "${KRAKEN_STORAGE_URL}"
      JAVA_OPTS: "-Dspring.profiles.active=docker -Xmx${KRAKEN_GATLING_XMX}"
    volumes:
      - type: volume
        source: gatling-volume
        target: /kraken/gatling/results

  kraken-gatling-log-parser:
    image: "octoperf/kraken-gatling-log-parser:${KRAKEN_VERSION}"
    container_name: "${KRAKEN_TASKID}-${KRAKEN_GATLING_SIDEKICK_NAME}_STARTING"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "${KRAKEN_SIDEKICK_CPU_LIMIT}"
          memory: "${KRAKEN_SIDEKICK_MEMORY_LIMIT}"
        reservations:
          cpus: "${KRAKEN_SIDEKICK_CPU_REQUEST}"
          memory: "${KRAKEN_SIDEKICK_MEMORY_REQUEST}"
    labels:
      com.kraken/taskId: "${KRAKEN_TASKID}"
      com.kraken/taskType: "${KRAKEN_TASKTYPE}"
      com.kraken/containerName: "${KRAKEN_TASKID}-${KRAKEN_GATLING_SIDEKICK_NAME}"
      com.kraken/hostId: "${KRAKEN_HOSTID}"
      com.kraken/label: "${KRAKEN_GATLING_SIDEKICK_LABEL}"
      com.kraken/description: "${KRAKEN_DESCRIPTION}"
      com.kraken/expectedCount: "${KRAKEN_EXPECTED_COUNT}"
      com.kraken/applicationId: "${KRAKEN_APPLICATION_ID}"
    environment:
      KRAKEN_CONTAINER_TASKID: "${KRAKEN_TASKID}"
      KRAKEN_CONTAINER_TASKTYPE: "${KRAKEN_TASKTYPE}"
      KRAKEN_CONTAINER_NAME: "${KRAKEN_TASKID}-${KRAKEN_GATLING_SIDEKICK_NAME}"
      KRAKEN_CONTAINER_HOSTID: "${KRAKEN_HOSTID}"
      KRAKEN_RUNTIME_URL: "${KRAKEN_RUNTIME_URL}"
      KRAKEN_STORAGE_URL: "${KRAKEN_STORAGE_URL}"
      KRAKEN_ANALYSIS_URL: "${KRAKEN_ANALYSIS_URL}"
      JAVA_OPTS: "-Dspring.profiles.active=docker -Xmx${KRAKEN_SIDEKICK_XMX}"
    volumes:
      - type: volume
        source: gatling-volume
        target: /kraken/gatling/results
        read_only: true
        volume:
          nocopy: true
    depends_on:
      - kraken-gatling-debugger

volumes:
  gatling-volume:
    name: ${KRAKEN_TASKID}-gatling-volume