kraken:
  runtime:
    server:
      configpath: tasks/docker/configuration.yaml
  influxdb:
    user: admin
    password: kraken
  security:
    realm: kraken
    web:
      id: kraken-web
    container:
      id: kraken-container
      secret: 6caa811c-5a41-4a53-aa5d-51c575330146
    api:
      id: kraken-api
      secret: c1ab32c0-0ba7-4289-b6c9-0ea1aa5ad1d4

spring:
  servlet:
    multipart:
      enabled: true # Whether to enable support of multipart uploads.
      file-size-threshold: 0B # Threshold after which files are written to disk.
      location: # Intermediate location of uploaded files.
      max-file-size: 500MB # Max file size.
      max-request-size: 500MB # Max request size.
      resolve-lazily: false # Whether to resolve the multipart request lazily at the time of file or parameter access.

logging:
  level:
    root: INFO
  com:
    kraken: INFO

server:
  port: 8082
  error:
    include-stacktrace: always

---
spring:
  profiles: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://kraken.local:9080/auth/realms/kraken
kraken:
  storage:
    url: http://kraken.local:8080
  analysis:
    url: http://kraken.local:8081
  runtime:
    url: http://kraken.local:8082
  influxdb:
    url: http://kraken.local:8086
  security:
    url: http://kraken.local:9080

---
spring:
  profiles: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://kraken-keycloak:9080/auth/realms/kraken

kraken:
  storage:
    url: http://kraken-storage:8080
  analysis:
    url: http://kraken-analysis:8081
  runtime:
    url: http://kraken-runtime:8082
  influxdb:
    url: http://kraken-influxdb:8086
  security:
    url: http://kraken-keycloak:9080