kraken:
  data: /home/kraken/data
  security:
    realm: kraken
    web:
      id: kraken-web

spring:
  servlet:
    multipart:
      enabled: true # Whether to enable support of multipart uploads.
      file-size-threshold: 0B # Threshold after which files are written to disk.
      location: # Intermediate location of uploaded files.
      max-file-size: 500MB # Max file size.
      max-request-size: 500MB # Max request size.
      resolve-lazily: false # Whether to resolve the multipart request lazily at the time of file or parameter access.

logging:
  level:
    root: INFO
  com:
    kraken: INFO

server:
  port: 8080
  error:
    include-stacktrace: always

---
spring:
  profiles: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://kraken.local:9080/auth/realms/kraken
kraken:
  data: devData/
  security:
    url: http://kraken.local:9080
  runtime:
    url:
---
spring:
  profiles: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://kraken-keycloak:9080/auth/realms/kraken

kraken:
  security:
    url: http://kraken-keycloak:9080
---
spring:
  profiles: kubernetes